apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "false"
  name: acrobot-release-as-service
  namespace: release-service
spec:
  application: acrobot
  target: rhtap-releng-tenant
